---
# tasks file for apache
#- name: install nginx
#  ansible.builtin.apt:
#    name: nginx
#    state: present
- name: install apache2
  ansible.builtin.apt:
    name: apache2
    state: present
    update_cache: yes
- name: start service apache2
  service:
    name: apache2
    state: started
    enabled: yes
- name: expose index html file
  ansible.builtin.copy:
    src: files/index.html
    dest: /var/www/html
    owner: root
    group: root
    mode: '0644'

